"""add due_date to tasks and activity_date to activities

Revision ID: 42bca4c6e35b
Revises: 0cbef026e498
Create Date: 2026-04-02 16:18:17.990581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bca4c6e35b'
down_revision: Union[str, Sequence[str], None] = '0cbef026e498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('activity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'activity_date')
    # ### end Alembic commands ###
